server:
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: always
    include-exception: true

logging:
  level:
    root: debug

environment:
  name: @project.name@
  version: @project.version@
  profile: "local"

