spring.application.name: Boilerplate
server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
    include-exception: false

logging:
  level:
    root: info

environment:
  name: @project.name@
  version: @project.version@
  profile: "default"

management:
  endpoints.web.exposure.include: "*"
  info.git.enabled: true
