spring.application.name: Boilerplate
server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
    include-exception: false

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  h2:
    console.enabled: true

logging:
  level:
    root: info

environment:
  profile: "default"

management:
  endpoints.web.exposure.include: "*"
  info.git.enabled: true
